### ISSUE TITLE
SciKitLearn python backend update breaks GH testing

### ISSUE THREAD

**Issue by odunbar** [CliMA/CalibrateEmulateSample.jl#176]
Old working version saw conda install 
`scikit-learn 1.1.1` and `scipy 1.8.1`
Now conda installs 
`scikit-learn 1.1.2` and `scipy 1.9.0`
I suspect the syntax for `pyimport` has changed

**Comment by tsj5** [comment]
This is puzzling -- the reason for the [broken test](https://github.com/CliMA/CalibrateEmulateSample.jl/runs/7909796642?check_suite_focus=true) appears to be that julia gets linked against one version of libstdc++, while the scikit-learn stuff wants a different version, as described [here](https://github.com/JuliaPy/PyCall.jl/issues/990). The workaround ([here](https://github.com/JuliaPy/PyCall.jl/issues/999)) is to modify `LD_PRELOAD`; apparently there's no less brittle fix, since the issue is with the third-party scikit-learn dependency. 

Aspects I'm unclear on:

- Is it necessary to use the `LD_PRELOAD` hack for *any* user of the scikit-learn backend on linux (seems likely)? It would be simple enough to modify `LD_PRELOAD` as part of the setup in Tests.yml, but this wouldn't be feasible to ask an end user to do every time they ran CES.
- What specific change to Manifest.toml brought in the incompatible scikit-learn? Conda.jl appears to pass through [version specifications](https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#package-match-specifications), so we could say `julia --project -e 'using Conda; Conda.add("scikit-learn=1.1.1")'`, but this means we'd be stuck maintaining a compatibility matrix between julia versions and scikit-learn versions.

**Comment by tsj5** [comment]
Pinning the versions of scikit-learn and scipy appears to get the linux test to pass (PR #177). Should we proceed along these lines?
