### ISSUE TITLE
LineSearches not in GaussianProcesses dependencies

### ISSUE THREAD

**Issue by benxro** [CliMA/CalibrateEmulateSample.jl#195]
Whenever I try to install CalibrateEmulateSample.jl exactly according to the documentation, I get some errors under the section "**Building the documentation locally**".

When I run: `$ julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'`, I get the following output:
```
Precompiling project...
  ✗ GaussianProcesses
  ✗ CalibrateEmulateSample
  14 dependencies successfully precompiled in 74 seconds (117 already precompiled)
  2 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages

```
When I then run: `$ julia --project=docs/ -e 'using Pkg; Pkg.precompile()'`, I get a very long error output, with the first few lines:
```
Precompiling project...
  ✗ GaussianProcesses
  ✗ CalibrateEmulateSample
  0 dependencies successfully precompiled in 11 seconds (131 already precompiled)

ERROR: The following 1 direct dependency failed to precompile:

CalibrateEmulateSample [95e48a1f-0bec-4818-9538-3db4340308e3]

Failed to precompile CalibrateEmulateSample [95e48a1f-0bec-4818-9538-3db4340308e3] to /home/ben/.julia/compiled/v1.7/CalibrateEmulateSample/jl_F1W2Ii.
ERROR: LoadError: ArgumentError: Package GaussianProcesses does not have LineSearches in its dependencies:
- If you have GaussianProcesses checked out for development and have
  added LineSearches as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with GaussianProcesses

```

I'm still not really familiar with Julia, but it seems like some dependency in the .toml file is missing.
So, when I add LineSearches like: `$ julia --project=docs/ -e 'using Pkg; Pkg.add("LineSearches")'` it updates the registry and subsequent runs of `Pkg.precompile()` and `Pkg.instantiate()`, do not cause errors anymore. Is this a valid fix?

Lastly, when I then run  `$ julia --project=docs/ docs/make.jl`, I get the output: 
```
WARNING: using GaussianProcesses.predict in module Emulators conflicts with an existing identifier.
WARNING: Method definition transition(AdvancedMH.MHSampler, AdvancedMH.DensityModel{F} where F, Any, Real) in module AdvancedMH at /home/ben/.julia/packages/AdvancedMH/rD4EE/src/mh-core.jl:67 overwritten in module MarkovChainMonteCarlo at /home/ben/prob-param-estimation/CalibrateEmulateSample.jl/src/MarkovChainMonteCarlo.jl:211.
  ** incremental compilation may be fatally broken for this module **

[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: skipped.
[ Info: ExpandTemplates: expanding markdown templates.
[ Info: CrossReferences: building cross-references.
[ Info: CheckDocument: running document checks.
[ Info: Populate: populating indices.
[ Info: RenderDocument: rendering document.
[ Info: HTMLWriter: rendering HTML pages.
```

Is this okay or should I worry that this might cause CES to misbehave? I mean it contains strong words like "may be fatally broken" and "conflicts with an existing identifier". I'm running on an Ubuntu 20.04 LTS. 

Kind regards 
Ben

**Comment by odunbar** [comment]
Hi Benxro, thanks for raising this! 

---
It's a curious error. I wonder whether this is due to the outdated `Manifest.toml` file that seems to be in our docs folder. This could cause some compatibility issues (e.g. it references an old version of GaussianProcesses.jl for example)

Could you try the following? 
- remove the `LineSearches` from the `Project.toml` that you have added
- delete `Manifest.toml` in the `docs/`  directory
- repeat the `julia --project=docs/ -e 'using Pkg; Pkg.precompile()` step (which will build a fresh new Manifest)

I will also remove the Manifest from the online repo. We used to use them across CliMA as a way of version control but found they quickly become unruly, so now we only work with `Project.toml` files. 
---

Note the GP / MH warnings are OK for now, @tsj5 is aware of these and we will get a fix in soon

Let me know how you get on!

**Comment by benxro** [comment]
Hey @odunbar ,

sorry for the late response. I just set up the project with the newest version (which includes your fix).
And it works flawlessly out of the box (apart from the GP / MH warning).

Thank you for fixing this!
