### ISSUE TITLE
find_mcmc_step! modifies MCMCObj

### ISSUE THREAD

**Issue by ilopezgp** [CliMA/CalibrateEmulateSample.jl#61]
The function `find_mcmc_step!` in `MCMC.jl` returns the step for optimal acceptance rate, but also advances the MCMC chain to a new state. 

This will be problematic when the starting MCMC step is set to a higher value than the optimal one. The reason is that at the initial iterations of the chain, the MCMC samples will move away from the region of maximum likelihood, which may increase significantly the amount of MCMC realizations needed to obtain a well-sampled posterior.

I propose changing `find_mcmc_step!` to `find_mcmc_step`, with no modification of the arguments, by using a copy of the MCMC object.

**Comment by odunbar** [comment]
It was initially set up so that you use one mcmc object to find the step size and then build a new object for the actual run. 

I think if you are worried about the fact it's at a new state. The easiest thing would be to put a `deepcopy` of `u0` into the constructor. Which could possibly be a one-liner to fix the problem.

After this fix, a non-modifying step size selection would be a good addition!
